server:
  port: 8011
spring:
  application:
    name: ApiGateway
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
    - id: users
      uri: lb://REGISTRATION-API
      predicates:
        - Path=/users/**
      
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      

      